App Install Page issue
osiset/laravel-shopify pull request #1074
Opened 2022-02-04 07:53 UTC by mudassirali007

fixed this [issue](https://github.com/osiset/laravel-shopify/issues/1071)

2022-03-01 15:39 UTC, lucasmichot commented on src/Storage/Commands/Shop.php
> +
please revert

2022-03-01 15:40 UTC, lucasmichot commented on src/Storage/Commands/Shop.php
> +
please revert

2022-03-01 15:41 UTC, lucasmichot requested changes
See comments
Also can you fix https://github.com/osiset/laravel-shopify/runs/5377785831?check_suite_focus=true ?

2022-09-10 07:22 UTC, Kyon147 commented
Looks like a fix was already implemented - so closing

2022-09-10 07:22 UTC, closed without merging