Verify theme support
osiset/laravel-shopify pull request #1198
Opened 2022-09-04 14:23 UTC by enmaboya

As you know lately, Shopify does not allow applications that only use script tags.

To work with the Online Store 2.0 you need to use "Theme app extensions".
But in this case you should not install script tags.
If the store has not yet updated the theme and is using the Online Store 1.0, script tags must be installed.

These changes solve this problem

2022-09-05 15:02 UTC, osiset requested changes

2022-09-05 15:03 UTC, osiset commented
@enmaboya While I disagree with Shopify introducing this, it just adds bloat and grunt work for people simply trying to make apps.. thanks for the changes, tests are in place and seem to be functioning. I am fine with this so long as it does indeed still support both methods. May need to add some documentation as well for people in the wiki.

2022-09-05 18:52 UTC, enmaboya commented on src/Actions/AuthenticateShop.php
> +    protected $verifyThemeSupport;
Yes, that's unnecessary.

2022-09-05 18:52 UTC, enmaboya commented on src/Actions/AuthenticateShop.php
> +    protected $verifyThemeSupport;
Yes, that's unnecessary.

2022-09-06 11:17 UTC, Kyon147 commented
Nice work on this @enmaboya, it is defo way too complicated than it needs to be (from Shopify)

It's worth mentioning that app embed blocks don't require script tags as they work with both v1 and v2 of themes. 

The dual script is specifically for `App Blocks` https://shopify.dev/apps/online-store/theme-app-extensions/extensions-framework#app-blocks. 

Might be worth putting that in the docs as well - as I agree with @osiset this is going to need some documentation as it's a pretty big uplight in functionality.

p.s code coverage seems to be failing though which needs looking at.

2022-09-07 07:43 UTC, enmaboya commented
@osiset @Kyon147 
I'll do the documentation and tests in the next few days

2022-09-08 14:17 UTC, osiset commented
@enmaboya Additionally, if app devs are expected to now install code snippets in an automated way to help with app blocks, where is this part of the code, or does it exist? Just trying to see if I can wrap my head around the flow.

2022-09-08 14:24 UTC, Kyon147 commented
@osiset the app blocks can be initiated using the Shopify CLI https://shopify.dev/apps/online-store/theme-app-extensions/getting-started#step-1-create-a-new-extension

This just scaffolds a directory inside your project root and any "updates" to the extension are the also published using the CLI. 

This is at least how I have used it recently when using an App Embed block but have not used the other type of block which requires this code @enmaboya has done but looking at the docs, the code for the extension works the same.

Here's a sample of the structure inside my directory after you run the CLI.
![image](https://user-images.githubusercontent.com/32519106/189147591-271ecb06-61e4-4c98-ae21-58e64e9fca3c.png)

2022-09-08 14:34 UTC, osiset commented
@Kyon147 Makes sense, I did it with a node project before, just wasnt sure how it would function with the Laravel setup, neat!

2022-09-09 14:23 UTC, osiset approved these changes

2022-09-09 14:27 UTC, osiset commented
@enmaboya I have added unit test for your theme helper service, resolved conflicts, and updated the documentation for it.

@Kyon147 I am current good with this too if you are. Tests are passing.

2022-09-11 13:53 UTC, enmaboya commented
@osiset Cool! 
I couldn't find time for them.

I also fixed conflicts with the main branch

2022-09-12 13:05 UTC, osiset approved these changes

2022-09-21 12:24 UTC, osiset commented
Thanks! Will await Kyron147 review before we merge.

2022-09-21 12:27 UTC, Kyon147 commented
Hey @osiset I'll carve sometime this week to take a look. 

Apologies work has been manic the last week or so!

2022-09-21 12:37 UTC, osiset commented
@Kyon147 No rush, no need for apologies :) been a hectic couple years myself, everyones busy ha

2022-10-01 09:41 UTC, Kyon147 approved these changes
This is some really good work. 

My only thoughts would be the deployment. 

As it is a massive change, I'd feel more comfortable making this it's own minor release without any other releases alongside it.

As there are some unpublished PRs already been pushed to master, we should release this after the current release is out.  It just means, if any breaking changes happen, people can just rollback the version number.

2022-10-03 16:30 UTC, osiset commented
@Kyon147 I agree.

2024-03-25 06:10 UTC, closed without merging