Adds Laravel 8 support
osiset/laravel-shopify pull request #569
Opened 2020-09-09 05:43 UTC by awebartisan

2020-09-09 08:11 UTC, Gummibeer requested changes
On top the matrix should include a prefer stable/lowest config and include the correct testbench version and exclude L5.8 on PHP7.4.

An example config is:
https://github.com/Astrotomic/laravel-translatable/blob/70811609331f10e3a068970632de1705133baa22/.github/workflows/run-tests.yml#L16

2020-09-09 08:11 UTC, Gummibeer commented on composer.json
> +        "php": ">=7.3",
Minimum PHP Version of the package itself hasn't changed!?

2020-09-09 08:11 UTC, Gummibeer commented on .github/workflows/ci.yml
> +        php-versions: ['7.3', '7.4']
PHP7.2 should be added to the Testmatrix.

2020-09-09 10:42 UTC, awebartisan commented
Need to wait until `orchestra/database` dependency support `illuminate/support ^8.0`.

2020-09-09 11:07 UTC, Gummibeer commented
There's already a dev version of v6.x
https://packagist.org/packages/orchestra/database
So a `minimum-stability: dev` in this package composer.json should solve it.

2020-09-09 12:44 UTC, Gummibeer approved these changes

2020-09-11 14:47 UTC, osiset commented
Thanks guys! This is very much appreciated!

2020-09-11 14:47 UTC, merged