UPDATE: configurable auth provider
osiset/laravel-shopify pull request #934
Opened 2021-08-06 16:31 UTC by vkislichenko

I'm sure there is a valid reasoning behind current logic of extending **User** model with shopify shop trait,
But I really do need them to be separate.

This PR provides one more shopify app config option `shop_auth_provider` ("users" by default)
Model is then taken from from config `auth.providers.{$config['shop_auth_provider']}.model`

Works if manual migrations are used and user table is replaced with custom one
Models provided by this package will still reference custom model using `user_id` columns, but it seems like a minor detail related to bigger refactoring.

2021-08-09 13:17 UTC, osiset commented
Sounds good to me! Please see the failed lint, adjust, and I'll merge :)

2021-09-03 17:26 UTC, vkislichenko commented
UPDATE: added config option `shop_auth_guard` 
It's mostly to prevent use of custom default auth guards (like jwt), but it might be also useful in other cases when `shop_auth_provider` specifies a custom model

2021-09-08 15:16 UTC, osiset requested changes
Couple small issues to correct linting, then can be merged.

2021-09-08 15:16 UTC, osiset commented on src/Http/Middleware/AuthProxy.php
> +            if(($guard = Util::getShopifyConfig('shop_auth_guard'))) {
@vkislichenko Fails linting here, needs a space after the if

2021-09-08 15:16 UTC, osiset commented on src/Http/Middleware/VerifyShopify.php
> +        if(($guard = Util::getShopifyConfig('shop_auth_guard'))) {
Same as previous @vkislichenko , needs space after if to pass linting.

2021-09-08 15:24 UTC, osiset approved these changes

2021-09-08 15:26 UTC, osiset commented
Checks passed, linting pass. Merging. Thanks @vkislichenko !

2021-09-08 15:26 UTC, merged

2021-11-08 10:33 UTC, salahy commented
What about the migrations ? they still change the user model

2021-11-08 12:50 UTC, vkislichenko commented
@salahy 
> What about the migrations ? they still change the user model

there's "Manual migrations" in config
and command `php artisan vendor:publish --tag=shopify-migrations` to push migrations to your app's folder so you're free to modify before migrating.

2022-01-24 05:58 UTC, nahid commented
When this changes will be released? @osiset